version: '2'
services:
  unifi:
    image: andrewglass3/unifi-5-8-22
    ports:
    - "8081:8081"
    - "8080:8080"
    - "8443:8443"
    - "8843:8843"
    - "3478:3478/udp"
    restart: always
    volumes:
            - /dockerstore/unifi/data:/var/lib/unifi
            - /dockerstore/unifi/logs:/var/log/unifi 
